language: node_js
node_js:
- '8'
before_script:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: ping@corpglory.com
  api_key:
    secure: svVXz5ktQkI31os4Wog0a9FmYbNdPTDDpKahoepKi3RtODkzi46o8f9FRAl4J+g3XJULb6/oj5J6tw024ctDFUNNO53AjMyK3mhu1oGSB4W+uosYXVZLaxkNcz4Ls16fBcPEpJOrUuq4PZFAxYLvo1o1DEvF9ci8AWoq1cYIZdMNgqhFqdNYec2Im19KgFm22N6PhRGq01G8at9luvtXujdKutYWea7YiYDiR28nyK0/LNFSj//NzebDxHZBC+knHdDzUXBaIXqUjJOytEoIa3kOD+eSnjUD2Q8Yx6YnR2le9W0gDAmYowJ9abYxNocfZZwvgURs1TZ4YYrfsJbkeDJ4kR99mcPUG2teUKNM/a2a5pAHbjWK3Q/3t8qquBfQH+UfAm1/+3lWHhp9RToUt0n+7qsOdDFAglOdjmaUEl9EsV2eHYDC43HyMrv5OuTVJVV+YouJBvkyvCVH+VSQdpfBOseCWCEvz2TZ1h5z7ebZ2SoREe20u2uscQHXe7wAs9RCeshT/wA11zyDK9BqJj7EzF8laFpD1qtKLsX2OwtlrK5gYtdKEK04VXBzpOdIWtQ36jpFX0SMnZ0B/cs3bZi0wdCaSRZ3RAWZ/4GzB7GYnyuYAbp1YN/JxaPzQPynOzptUfYXVWogV3V2yUltHnpfWnpjFR2e5NpTSNt89rs=
  on:
    tags: true
notifications:
  email: false
